/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewsItem = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const QuizScore = IDL.Record({
  'total' : IDL.Nat,
  'user' : IDL.Text,
  'score' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addNewsItem' : IDL.Func([NewsItem], [IDL.Nat], []),
  'addQuestion' : IDL.Func([QuizQuestion], [IDL.Nat], []),
  'deleteNewsItem' : IDL.Func([IDL.Nat], [], []),
  'getMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getNewsItem' : IDL.Func([IDL.Nat], [NewsItem], ['query']),
  'getNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getScores' : IDL.Func([], [IDL.Vec(QuizScore)], ['query']),
  'seedData' : IDL.Func([], [], []),
  'submitMessage' : IDL.Func([ContactMessage], [IDL.Nat], []),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'updateNewsItem' : IDL.Func([IDL.Nat, NewsItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewsItem = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const QuizScore = IDL.Record({
    'total' : IDL.Nat,
    'user' : IDL.Text,
    'score' : IDL.Nat,
  });
  
  return IDL.Service({
    'addNewsItem' : IDL.Func([NewsItem], [IDL.Nat], []),
    'addQuestion' : IDL.Func([QuizQuestion], [IDL.Nat], []),
    'deleteNewsItem' : IDL.Func([IDL.Nat], [], []),
    'getMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getNewsItem' : IDL.Func([IDL.Nat], [NewsItem], ['query']),
    'getNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getScores' : IDL.Func([], [IDL.Vec(QuizScore)], ['query']),
    'seedData' : IDL.Func([], [], []),
    'submitMessage' : IDL.Func([ContactMessage], [IDL.Nat], []),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'updateNewsItem' : IDL.Func([IDL.Nat, NewsItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };