/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface NewsItem {
  'title' : string,
  'date' : string,
  'summary' : string,
  'category' : string,
}
export interface QuizQuestion {
  'question' : string,
  'correctIndex' : bigint,
  'explanation' : string,
  'options' : Array<string>,
}
export interface QuizScore {
  'total' : bigint,
  'user' : string,
  'score' : bigint,
}
export interface _SERVICE {
  'addNewsItem' : ActorMethod<[NewsItem], bigint>,
  'addQuestion' : ActorMethod<[QuizQuestion], bigint>,
  'deleteNewsItem' : ActorMethod<[bigint], undefined>,
  'getMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getNewsItem' : ActorMethod<[bigint], NewsItem>,
  'getNewsItems' : ActorMethod<[], Array<NewsItem>>,
  'getQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getScores' : ActorMethod<[], Array<QuizScore>>,
  'seedData' : ActorMethod<[], undefined>,
  'submitMessage' : ActorMethod<[ContactMessage], bigint>,
  'submitScore' : ActorMethod<[string, bigint, bigint], undefined>,
  'updateNewsItem' : ActorMethod<[bigint, NewsItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];