/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuizScore {
    total: bigint;
    user: string;
    score: bigint;
}
export interface ContactMessage {
    name: string;
    email: string;
    message: string;
}
export interface NewsItem {
    title: string;
    date: string;
    summary: string;
    category: string;
}
export interface QuizQuestion {
    question: string;
    correctIndex: bigint;
    explanation: string;
    options: Array<string>;
}
export interface backendInterface {
    addNewsItem(newsItem: NewsItem): Promise<bigint>;
    addQuestion(question: QuizQuestion): Promise<bigint>;
    deleteNewsItem(id: bigint): Promise<void>;
    getMessages(): Promise<Array<ContactMessage>>;
    getNewsItem(id: bigint): Promise<NewsItem>;
    getNewsItems(): Promise<Array<NewsItem>>;
    getQuestions(): Promise<Array<QuizQuestion>>;
    getScores(): Promise<Array<QuizScore>>;
    seedData(): Promise<void>;
    submitMessage(message: ContactMessage): Promise<bigint>;
    submitScore(user: string, score: bigint, total: bigint): Promise<void>;
    updateNewsItem(id: bigint, newsItem: NewsItem): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addNewsItem(arg0: NewsItem): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsItem(arg0);
            return result;
        }
    }
    async addQuestion(arg0: QuizQuestion): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0);
            return result;
        }
    }
    async deleteNewsItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNewsItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNewsItem(arg0);
            return result;
        }
    }
    async getMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return result;
        }
    }
    async getNewsItem(arg0: bigint): Promise<NewsItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsItem(arg0);
            return result;
        }
    }
    async getNewsItems(): Promise<Array<NewsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsItems();
            return result;
        }
    }
    async getQuestions(): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestions();
            return result;
        }
    }
    async getScores(): Promise<Array<QuizScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScores();
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async submitMessage(arg0: ContactMessage): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMessage(arg0);
            return result;
        }
    }
    async submitScore(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitScore(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitScore(arg0, arg1, arg2);
            return result;
        }
    }
    async updateNewsItem(arg0: bigint, arg1: NewsItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsItem(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
